
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/denverdino/aliyungo"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  branch = "release-1.9"
  name = "k8s.io/api"

#[[constraint]]
#  branch = "release-1.9"
#  name = "k8s.io/apiextensions-apiserver"

[[constraint]]
  branch = "release-1.9"
  name = "k8s.io/apimachinery"

[[constraint]]
  branch = "release-1.9"
  name = "k8s.io/apiserver"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.9"

[[override]]
  name = "github.com/patrickmn/go-cache"
  branch = "master"

[[override]]
  branch = "release-6.0"
  name = "k8s.io/client-go"

[[override]]
  revision = "545102ea07aa9796f189d82f606b7c27d7aa3ed3"
  name = "github.com/docker/distribution"

